env:
  jest: true
  node: true
parser: babel-eslint
extends:
  - eslint:recommended
  - plugin:prettier/recommended
# I added Prettier configuration
prettier/prettier:
  parenSpacing: false # Disable parentheses spacing
